# **Movie Analysis Project**

## **Dataset Overview**
The dataset is taken from *Kaggle.com* and contains ***1000 top-rated IMDb movies*** with details like *rating*, *genre*, and *cast*.

## **Objective**
The Objective of Cleaning and Analysis of this Dataset is to find the watch Trends, Relation and Impact of Genre, Director, Star Cast on the Revenue and Performance of the Movie.

## Key Features
- Title
- Year of release
- Star Cast
- IMDB rating
- Gross revenue

# **Libraries Used and Loading Dataset**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

Og_ds = pd.read_csv('C:/Users/Dell/Downloads/IMDb Top 1000.csv')
Og_ds.info()
Og_ds.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

       IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

# **Reading Datset**

In [2]:
Og_ds.head(5)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

# **Data Cleaning**
## Slicing of Rows from the Dataset

In [3]:
Cleaned_ds1 = Og_ds.iloc[:140]
Cleaned_ds2= Og_ds.iloc[-16:]
Cleaned_ds= pd.concat([Cleaned_ds1, Cleaned_ds2],axis=0)
Cleaned_ds.info()
Cleaned_ds.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 156 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    156 non-null    object
 1   Series_Title   156 non-null    object
 2   Released_Year  156 non-null    object
 3   Certificate    146 non-null    object
 4   Runtime        156 non-null    object
 5   Genre          156 non-null    object
 6   IMDB_Rating    156 non-null    float64
 7   Overview       156 non-null    object
 8   Meta_score     127 non-null    float64
 9   Director       156 non-null    object
 10  Star1          156 non-null    object
 11  Star2          156 non-null    object
 12  Star3          156 non-null    object
 13  Star4          156 non-null    object
 14  No_of_Votes    156 non-null    int64
 15  Gross          132 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 20.7+ KB

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

# **Data Manupilation**

## Identifying Null Values in Individual Columns

In [4]:
Cleaned_ds.isna().sum()

Poster_Link       0
Series_Title      0
Released_Year     0
Certificate      10
Runtime           0
Genre             0
IMDB_Rating       0
Overview          0
Meta_score       29
Director          0
Star1             0
Star2             0
Star3             0
Star4             0
No_of_Votes       0
Gross            24
dtype: int64

# Removing Unnecessary Columns

In [5]:
Cleaned_ds.drop(['Poster_Link','Certificate','Runtime','Overview','Meta_score','Star3','Star4'],axis=1, inplace=True)
Cleaned_ds.columns.to_list()

['Series_Title',
 'Released_Year',
 'Genre',
 'IMDB_Rating',
 'Director',
 'Star1',
 'Star2',
 'No_of_Votes',
 'Gross']

## Checking for Duplicate Values

In [6]:
Cleaned_ds.duplicated().sum()

np.int64(0)

## Previewing Duplicate Values

In [7]:
Cleaned_ds[Cleaned_ds.duplicated()] # No duplicates

Empty DataFrame
Columns: [Series_Title, Released_Year, Genre, IMDB_Rating, Director, Star1, Star2, No_of_Votes, Gross]
Index: []

## Checking for Rows with Null Values

In [8]:
Cleaned_ds[Cleaned_ds.isnull().any(axis=1)]

,Series_Title,Released_Year,Genre,IMDB_Rating,Director,Star1,Star2,No_of_Votes,Gross
18,Hamilton,2020,"Biography, Drama, History",8.6,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,55291,NaN
20,Soorarai Pottru,2020,Drama,8.6,Sudha Kongara,Suriya,Madhavan,54995,NaN
30,Seppuku,1962,"Action, Drama, Mystery",8.6,Masaki Kobayashi,Tatsuya Nakadai,Akira Ishihama,42004,NaN
32,It's a Wonderful Life,1946,"Drama, Family, Fantasy",8.6,Frank Capra,James Stewart,Donna Reed,405801,NaN
46,Hotaru no haka,1988,"Animation, Drama, War",8.5,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,235231,NaN
54,Ayla: The Daughter of War,2017,"Biography, Drama, History",8.4,Can Ulkay,Erdem Can,Çetin Tekindor,34112,NaN
55,Vikram Vedha,2017,"Action, Crime, Drama",8.4,Gayatri,Pushkar,Madhavan,28401,NaN
76,Anand,1971,"Drama, Musical",8.4,Hrishikesh Mukherjee,Rajesh Khanna,Amitabh Bachchan,30273,NaN
77,Tengoku to jigoku,1963,"Crime, Drama, Mystery",8.4,Akira Kurosawa,Toshirô Mifune,Yutaka Sada,34357,NaN
80,Paths of Glory,1957,"Drama, War",8.4,Stanley Kubrick,Kirk Douglas,Ralph Meeker,178092,NaN
82,Sunset Blvd.,1950,"Drama, Film-Noir",8.4,Billy Wilder,William Holden,Gloria Swanson,201632,NaN
85,Tumbbad,2018,"Drama, Fantasy, Horror",8.3,Rahi Anil Barve,Anand Gandhi,Adesh Prasad,27793,NaN
87,Drishyam,2013,"Crime, Drama, Thriller",8.3,Jeethu Joseph,Mohanlal,Meena,30722,NaN
91,Miracle in cell NO.7,2019,Drama,8.3,Mehmet Ada Öztekin,Aras Bulut Iynemli,Nisa Sofiya Aksongur,33935,NaN
92,Babam ve Oglum,2005,"Drama, Family",8.3,Çagan Irmak,Çetin Tekindor,Fikret Kuskan,78925,NaN
105,Idi i smotri,1985,"Drama, Thriller, War",8.3,Elem Klimov,Aleksey Kravchenko,Olga Mironova,59056,NaN
130,K.G.F: Chapter 1,2018,"Action, Drama",8.2,Prashanth Neel,Yash,Srinidhi Shetty,36680,NaN
135,Klaus,2019,"Animation, Adventure, Comedy",8.2,Sergio Pablos,Carlos Martínez López,Jason Schwartzman,104761,NaN
986,Watership Down,1978,"Animation, Adventure, Drama",7.6,Martin Rosen,John Hubley,John Hurt,33656,NaN
993,Blowup,1966,"Drama, Mystery, Thriller",7.6,Michelangelo Antonioni,David Hemmings,Vanessa Redgrave,56513,NaN
995,Breakfast at Tiffany's,1961,"Comedy, Drama, Romance",7.6,Blake Edwards,Audrey Hepburn,George Peppard,166544,NaN
996,Giant,1956,"Drama, Western",7.6,George Stevens,Elizabeth Taylor,Rock Hudson,34075,NaN
998,Lifeboat,1944,"Drama, War",7.6,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,26471,NaN
999,The 39 Steps,1935,"Crime, Mystery, Thriller",7.6,Alfred Hitchcock,Robert Donat,Madeleine Carroll,51853,NaN

## Filling Null Values in ***Gross***

Creating a Backup In Case of Errors

In [9]:
#Cleaned_ds['Gross_backup'] = Cleaned_ds['Gross'].copy()
Cleaned_ds['Gross'].head(5)

0     28,341,469
1    134,966,411
2    534,858,444
3     57,300,000
4      4,360,000
Name: Gross, dtype: object

Checking DataType of Gross

In [10]:
Cleaned_ds['Gross'].dtypes

dtype('O')

Checking Unique Value for Dtype ***Object***

In [11]:
Cleaned_ds['Gross'].unique()

array(['28,341,469', '134,966,411', '534,858,444', '57,300,000',
       '4,360,000', '377,845,905', '107,928,762', '96,898,818',
       '292,576,195', '37,030,102', '315,544,750', '330,252,182',
       '6,100,000', '342,551,365', '171,479,930', '46,836,394',
       '290,475,067', '112,000,000', nan, '53,367,844', '188,020,017',
       '7,563,397', '10,055,859', '216,540,909', '136,801,374',
       '57,598,247', '100,125,643', '130,742,922', '322,740,140',
       '269,061', '335,451,311', '13,092,000', '13,182,281', '53,089,891',
       '132,384,315', '32,572,577', '187,705,427', '6,719,864',
       '23,341,568', '19,501,238', '422,783,777', '204,843,350',
       '11,990,401', '210,609,762', '5,321,508', '32,000,000',
       '1,024,560', '163,245', '19,181', '1,661,096', '5,017,246',
       '12,391,761', '190,241,310', '858,373,000', '678,815,482',
       '209,726,015', '162,805,434', '448,139,099', '6,532,908',
       '1,223,869', '223,808,164', '11,286,112', '707,481', '25,544,867',
       '2,375,308', '248,159,971', '44,017,374', '83,471,511',
       '78,900,000', '275,902', '8,175,000', '36,764,313', '288,475',
       '159,227,644', '1,373,943', '687,185', '7,098,492', '6,857,096',
       '120,540,719', '34,400,301', '33,225,499', '30,328,156',
       '3,635,482', '130,096,601', '138,433,435', '933,933',
       '191,796,233', '75,600,000', '2,832,029', '46,357,676',
       '85,160,248', '51,973,029', '45,598,982', '309,125,409',
       '11,487,676', '28,262,574', '159,600,000', '6,207,725',
       '56,954,992', '15,000,000', '44,824,144', '18,600,000',
       '13,275,000', '3,200,000', '8,819,028', '55,240', '332,930',
       '5,720,000', '1,585,634', '28,877', '1,236,166', '5,450,000',
       '898,575', '4,186,168', '85,080,171', '54,513,740', '342,370',
       '20,186,659', '739,478', '1,429,534', '144,501', '1,626,289',
       '76,657,000', '43,000,000', '35,000,000', '132,088,635', '959,000',
       '696,690', '1,378,435', '141,843,612', '13,780,024', '30,500,000'],
      dtype=object)

**Removing Commas and Spaces Created by them**

In [12]:
Cleaned_ds['Gross'] = Cleaned_ds['Gross'].str.replace('[,]', '', regex=True).str.strip()
Cleaned_ds['Gross'] = Cleaned_ds['Gross'].replace('', pd.NA)

Checking Unique Values again after Replacment

In [13]:
Cleaned_ds['Gross'].unique()

array(['28341469', '134966411', '534858444', '57300000', '4360000',
       '377845905', '107928762', '96898818', '292576195', '37030102',
       '315544750', '330252182', '6100000', '342551365', '171479930',
       '46836394', '290475067', '112000000', nan, '53367844', '188020017',
       '7563397', '10055859', '216540909', '136801374', '57598247',
       '100125643', '130742922', '322740140', '269061', '335451311',
       '13092000', '13182281', '53089891', '132384315', '32572577',
       '187705427', '6719864', '23341568', '19501238', '422783777',
       '204843350', '11990401', '210609762', '5321508', '32000000',
       '1024560', '163245', '19181', '1661096', '5017246', '12391761',
       '190241310', '858373000', '678815482', '209726015', '162805434',
       '448139099', '6532908', '1223869', '223808164', '11286112',
       '707481', '25544867', '2375308', '248159971', '44017374',
       '83471511', '78900000', '275902', '8175000', '36764313', '288475',
       '159227644', '1373943', '687185', '7098492', '6857096',
       '120540719', '34400301', '33225499', '30328156', '3635482',
       '130096601', '138433435', '933933', '191796233', '75600000',
       '2832029', '46357676', '85160248', '51973029', '45598982',
       '309125409', '11487676', '28262574', '159600000', '6207725',
       '56954992', '15000000', '44824144', '18600000', '13275000',
       '3200000', '8819028', '55240', '332930', '5720000', '1585634',
       '28877', '1236166', '5450000', '898575', '4186168', '85080171',
       '54513740', '342370', '20186659', '739478', '1429534', '144501',
       '1626289', '76657000', '43000000', '35000000', '132088635',
       '959000', '696690', '1378435', '141843612', '13780024', '30500000'],
      dtype=object)

**Converting Gross from Object type to Numeric type**

In [14]:
Cleaned_ds['Gross'] = pd.to_numeric(Cleaned_ds['Gross'], errors='coerce')
Cleaned_ds['Gross'].head(5)

0     28341469.0
1    134966411.0
2    534858444.0
3     57300000.0
4      4360000.0
Name: Gross, dtype: float64

**Checking Dtype again for Verification**

In [15]:
Cleaned_ds['Gross'].dtypes

dtype('float64')

Checking Null Values before Filling

In [16]:
Cleaned_ds['Gross'].isna().sum()

np.int64(24)

**Filling NaN with Median in Gross**

In [17]:
Cleaned_ds['Gross'] = Cleaned_ds['Gross'].fillna(Cleaned_ds['Gross'].median())
Cleaned_ds['Gross'].isna().sum()

np.int64(0)

Checking Null Value after Filling

In [18]:
Cleaned_ds['Gross'].isnull().sum()

np.int64(0)

In [19]:
Cleaned_ds['Gross'].head(5)

0     28341469.0
1    134966411.0
2    534858444.0
3     57300000.0
4      4360000.0
Name: Gross, dtype: float64

Rows with Values of Gross Changed to Median

In [ ]:
median_value = Cleaned_ds['Gross'].median()
Cleaned_ds[Cleaned_ds['Gross'] == median_value][['Gross']]

          Gross
18   32286288.5
20   32286288.5
30   32286288.5
32   32286288.5
46   32286288.5
54   32286288.5
55   32286288.5
76   32286288.5
77   32286288.5
80   32286288.5
82   32286288.5
85   32286288.5
87   32286288.5
91   32286288.5
92   32286288.5
105  32286288.5
130  32286288.5
135  32286288.5
986  32286288.5
993  32286288.5
995  32286288.5
996  32286288.5
998  32286288.5
999  32286288.5

Checking Movie with Same Gross

In [21]:
Cleaned_ds[Cleaned_ds['Gross'] == Cleaned_ds['Gross'].median()][['Series_Title', 'Gross']]

                  Series_Title       Gross
18                    Hamilton  32286288.5
20             Soorarai Pottru  32286288.5
30                     Seppuku  32286288.5
32       It's a Wonderful Life  32286288.5
46              Hotaru no haka  32286288.5
54   Ayla: The Daughter of War  32286288.5
55                Vikram Vedha  32286288.5
76                       Anand  32286288.5
77           Tengoku to jigoku  32286288.5
80              Paths of Glory  32286288.5
82                Sunset Blvd.  32286288.5
85                     Tumbbad  32286288.5
87                    Drishyam  32286288.5
91        Miracle in cell NO.7  32286288.5
92              Babam ve Oglum  32286288.5
105               Idi i smotri  32286288.5
130           K.G.F: Chapter 1  32286288.5
135                      Klaus  32286288.5
986             Watership Down  32286288.5
993                     Blowup  32286288.5
995     Breakfast at Tiffany's  32286288.5
996                      Giant  32286288.5
998                   Lifeboat  32286288.5
999               The 39 Steps  32286288.5

**Renaming Columns**

In [22]:
Cleaned_ds = Cleaned_ds.rename(columns={
    'Series_Title': 'Movie Title',
    'Released_Year': 'Release Year',
    'Genre': 'Genres',
    'IMDB_Rating': 'IMDb Rating',
    'Star1': 'Actor 1',
    'Star2': 'Actor 2',
    'No_of_Votes': 'User Votes',
    'Gross': 'Box Office Collections',
})
Cleaned_ds.columns.to_list()

['Movie Title',
 'Release Year',
 'Genres',
 'IMDb Rating',
 'Director',
 'Actor 1',
 'Actor 2',
 'User Votes',
 'Box Office Collections']

In [23]:
Cleaned_ds.to_csv('Cleaned Dataset.csv',index=False)

In [24]:
temp=pd.read_csv('Cleaned Dataset.csv')
temp.head(5)

,Movie Title,Release Year,Genres,IMDb Rating,Director,Actor 1,Actor 2,User Votes,Box Office Collections
0,The Shawshank Redemption,1994,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,2343110,28341469.0
1,The Godfather,1972,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,1620367,134966411.0
2,The Dark Knight,2008,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,2303232,534858444.0
3,The Godfather: Part II,1974,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,1129952,57300000.0
4,12 Angry Men,1957,"Crime, Drama",9.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,689845,4360000.0